Repository depromeet/SPOT-Android, pull requests merged in 2024-09, with the labels that each got.

#176 [FIX] 스크랩, 홈 로직 수정
  presentation/src/main/java/com/dpm/presentation/home/HomeActivity.kt
  presentation/src/main/java/com/dpm/presentation/scrap/ScrapActivity.kt
  presentation/src/main/java/com/dpm/presentation/scrap/ScrapDetailPictureFragment.kt
  presentation/src/main/java/com/dpm/presentation/scrap/viewmodel/ScrapViewModel.kt
Labels: 🐞Fix, 💪개발자_노균욱

#177 [FIX] 테이블석 예외 처리 수정
  presentation/src/main/java/com/dpm/presentation/seatreview/dialog/main/SelectSeatDialog.kt
Labels: 🐞Fix, 🦔개발자_박민주

#181 [FIX] 팀 선택하는 화면 간격 수정 및 닉네임 레이아웃 수정
  presentation/src/main/java/com/dpm/presentation/login/ui/TeamSelectActivity.kt
  presentation/src/main/res/layout/activity_signup_complete.xml
Labels: 🐞Fix, 🍽개발자_윤성식
