Repository depromeet/SPOT-Android, pull requests merged in 2024-07, with the labels that each got.

#11 [#10/FIX] Hilt 모듈 어노테이션 변경작업
  .gitignore
  app/src/main/java/com/depromeet/spot/di/DataSourceModule.kt
  app/src/main/java/com/depromeet/spot/di/RepositoryModule.kt
Labels: 🐞Fix, 🍽개발자_윤성식

#17 [BSVR-106/FEAT] 시야 찾기 UI 2차 구현
  app/src/main/AndroidManifest.xml
  buildSrc/src/main/kotlin/Dependencies.kt
  buildSrc/src/main/kotlin/Versions.kt
  core/designsystem/src/main/java/com/depromeet/designsystem/SpotAppbar.kt
  core/designsystem/src/main/res/layout/spot_appbar.xml
  core/designsystem/src/main/res/values/attrs.xml
  presentation/build.gradle.kts
  presentation/src/main/java/com/depromeet/presentation/extension/ExtraExt.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/StadiumActivity.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/StadiumDetailActivity.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/StadiumDetailPictureFragment.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/compose/CustomTooltip.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/compose/KeywordCard.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/compose/KeywordFlowRow.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/compose/LevelCard.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/compose/MonthlyViewCard.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/compose/StadiumAreaText.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/compose/StadiumDetailScreen.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/compose/StadiumEmptyReviewContent.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/compose/StadiumHeaderContent.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/compose/StadiumKeywordContent.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/compose/StadiumKeywordRow.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/compose/StadiumPictureViewPager.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/compose/StadiumReviewContent.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/compose/StadiumSeatCheckBox.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/compose/StadiumViewReviewHeader.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/compose/detailpicture/StadiumDetailPictureScreen.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/compose/detailpicture/StadiumDetailPictureViewPager.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/sample/Keyword.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/sample/Review.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/sample/Seat.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/sample/StadiumArea.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/sample/samples.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/sample/stadiums.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/viewmodel/StadiumDetailViewModel.kt
  presentation/src/main/res/drawable/ic_empty_review.xml
  presentation/src/main/res/drawable/ic_horizontal_dots.xml
  presentation/src/main/res/drawable/ic_up.xml
  presentation/src/main/res/drawable/rect_white_fill_gray100_line_8.xml
  presentation/src/main/res/layout/activity_stadium.xml
  presentation/src/main/res/layout/activity_stadium_detail.xml
  presentation/src/main/res/layout/fragment_stadium_detail_picture.xml
  presentation/src/main/res/values/colors.xml
Labels: 🎇Feature, 🦖개발자_조관희

#22 [BSVR-110/FEAT] 시야 찾기 야구장 로직 및 재구현
  app/build.gradle.kts
  app/src/main/java/com/depromeet/spot/di/DataSourceModule.kt
  app/src/main/java/com/depromeet/spot/di/RepositoryModule.kt
  app/src/main/java/com/depromeet/spot/di/RetrofitModule.kt
  app/src/main/java/com/depromeet/spot/di/ServiceModule.kt
  data/src/main/java/com/depromeet/data/datasource/WebSvgDataSource.kt
  data/src/main/java/com/depromeet/data/datasource/remote/WebSvgDataSourceImpl.kt
  data/src/main/java/com/depromeet/data/remote/WebSvgApiService.kt
  data/src/main/java/com/depromeet/data/repository/WebSvgRepositoryImpl.kt
  domain/src/main/java/com/depromeet/domain/repository/WebSvgRepository.kt
  presentation/src/main/assets/web/stadium.js
  presentation/src/main/java/com/depromeet/presentation/viewfinder/StadiumActivity.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/viewmodel/StadiumViewModel.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/web/AndroidBridge.kt
Labels: 🎇Feature, 🦖개발자_조관희

#24 [BSVR-108/FEAT] 시야 찾기 UI 3차 구현
  core/src/main/java/com/depromeet/core/base/BindingBottomSheetDialog.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/StadiumDetailActivity.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/compose/StadiumDetailScreen.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/compose/StadiumHeaderContent.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/compose/StadiumReviewContent.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/compose/StadiumSeatCheckBox.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/dialog/ReportDialog.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/dialog/StadiumFilterMonthsDialog.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/dialog/StadiumSelectSeatDialog.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/viewmodel/StadiumDetailViewModel.kt
  presentation/src/main/res/drawable/sel_seat_button.xml
  presentation/src/main/res/layout/fragment_report_dialog.xml
  presentation/src/main/res/layout/fragment_stadium_filter_months_dialog.xml
  presentation/src/main/res/layout/fragment_stadium_select_seat_dialog.xml
  presentation/src/main/res/values/themes.xml
Labels: 🎇Feature, 🦖개발자_조관희

#30 [BSVR-125/FEAT] 시야 찾기 서버 통신 1차 구현
  app/src/main/java/com/depromeet/spot/di/DataSourceModule.kt
  app/src/main/java/com/depromeet/spot/di/RepositoryModule.kt
  app/src/main/java/com/depromeet/spot/di/ServiceModule.kt
  data/src/main/java/com/depromeet/data/datasource/ViewfinderDataSource.kt
  data/src/main/java/com/depromeet/data/datasource/remote/ViewfinderDataSourceImpl.kt
  data/src/main/java/com/depromeet/data/mapper/ViewfinderMapper.kt
  data/src/main/java/com/depromeet/data/model/response/viewfinder/BlockReviewResponseDto.kt
  data/src/main/java/com/depromeet/data/model/response/viewfinder/StadiumResponseDto.kt
  data/src/main/java/com/depromeet/data/model/response/viewfinder/StadiumsResponseDto.kt
  data/src/main/java/com/depromeet/data/remote/ViewfinderService.kt
  data/src/main/java/com/depromeet/data/repository/ViewfinderRepositoryImpl.kt
  data/src/main/java/com/depromeet/data/repository/WebSvgRepositoryImpl.kt
  domain/src/main/java/com/depromeet/domain/entity/response/viewfinder/BlockReviewResponse.kt
  domain/src/main/java/com/depromeet/domain/entity/response/viewfinder/StadiumResponse.kt
  domain/src/main/java/com/depromeet/domain/entity/response/viewfinder/StadiumsResponse.kt
  domain/src/main/java/com/depromeet/domain/repository/ViewfinderRepository.kt
  domain/src/main/java/com/depromeet/domain/repository/WebSvgRepository.kt
  presentation/src/main/java/com/depromeet/presentation/mapper/KeywordMapper.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/StadiumActivity.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/StadiumDetailActivity.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/StadiumDetailPictureFragment.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/StadiumSelectionActivity.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/adapter/StadiumSelectionAdapter.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/compose/StadiumDetailScreen.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/compose/StadiumHeaderContent.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/compose/StadiumKeywordContent.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/compose/StadiumKeywordRow.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/compose/StadiumReviewContent.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/compose/detailpicture/StadiumDetailPictureScreen.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/compose/detailpicture/StadiumDetailPictureViewPager.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/viewholder/StadiumSelectionViewHolder.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/viewmodel/StadiumDetailViewModel.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/viewmodel/StadiumSelectionViewModel.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/viewmodel/StadiumViewModel.kt
Labels: 🎇Feature, 🦖개발자_조관희

#34 [BSVR-147/FEAT] 로그인 회원가입 인증 로직 추가
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/depromeet/spot/MyApp.kt
  app/src/main/java/com/depromeet/spot/di/DataSourceModule.kt
  app/src/main/java/com/depromeet/spot/di/RepositoryModule.kt
  app/src/main/java/com/depromeet/spot/di/RetrofitModule.kt
  app/src/main/java/com/depromeet/spot/di/ServiceModule.kt
  app/src/main/java/com/depromeet/spot/di/SharedPreferenceModule.kt
  buildSrc/build/kotlin/buildSrcjar-classes.txt
  buildSrc/build/kotlin/compileKotlin/cacheable/last-build.bin
  buildSrc/build/kotlin/compileKotlin/local-state/build-history.bin
  buildSrc/build/libs/buildSrc.jar
  buildSrc/src/main/kotlin/Dependencies.kt
  buildSrc/src/main/kotlin/Versions.kt
  data/src/main/java/com/depromeet/data/datasource/SignupRemoteDataSource.kt
  data/src/main/java/com/depromeet/data/datasource/remote/SignupRemoteDataSourceImpl.kt
  data/src/main/java/com/depromeet/data/intercepter/AuthInterceptor.kt
  data/src/main/java/com/depromeet/data/model/request/signup/RequestPostSignupDto.kt
  data/src/main/java/com/depromeet/data/model/response/signup/ResponsePostSignupDto.kt
  data/src/main/java/com/depromeet/data/preference/SharedPreference.kt
  data/src/main/java/com/depromeet/data/remote/SignupService.kt
  data/src/main/java/com/depromeet/data/repository/SignupRepositoryImpl.kt
  domain/src/main/java/com/depromeet/domain/entity/request/signup/PostSignupModel.kt
  domain/src/main/java/com/depromeet/domain/entity/response/signup/SignupTokenModel.kt
  domain/src/main/java/com/depromeet/domain/preference/NetworkPreference.kt
  domain/src/main/java/com/depromeet/domain/repository/SignupRepository.kt
  presentation/build.gradle.kts
  presentation/src/main/java/com/depromeet/presentation/login/SelectStadium.kt
  presentation/src/main/java/com/depromeet/presentation/login/TeamSelectAdapter.kt
  presentation/src/main/java/com/depromeet/presentation/login/ui/KakaoSignupFragment.kt
  presentation/src/main/java/com/depromeet/presentation/login/ui/NicknameInputFragment.kt
  presentation/src/main/java/com/depromeet/presentation/login/ui/SignUpCompleteActivity.kt
  presentation/src/main/java/com/depromeet/presentation/login/ui/SingUpActivity.kt
  presentation/src/main/java/com/depromeet/presentation/login/ui/TeamSelectFragment.kt
  presentation/src/main/java/com/depromeet/presentation/login/viewmodel/SignUpViewModel.kt
  presentation/src/main/res/drawable/ic_kakao_logo.xml
  presentation/src/main/res/drawable/ic_signup_complete_main.png
  presentation/src/main/res/layout/activity_signup.xml
  presentation/src/main/res/layout/activity_signup_complete.xml
  presentation/src/main/res/layout/fragment_kakao_signup.xml
  presentation/src/main/res/layout/fragment_nickname_input.xml
  presentation/src/main/res/layout/fragment_team_select.xml
  presentation/src/main/res/layout/item_baseball_team.xml
  presentation/src/main/res/layout/item_select_team.xml
  settings.gradle.kts
Labels: 🎇Feature, 🍽개발자_윤성식

#46 [FIX] Green 색상 컬러 변경
  core/designsystem/src/main/res/values/colors.xml
Labels: 🐞Fix, 🦖개발자_조관희

#48 [FIX] Typo fontFamily 적용 수정
  core/designsystem/src/main/res/values/appearances.xml
Labels: 🐞Fix, 🦔개발자_박민주

#50 [FIX] text apperance 일괄 수정
  core/designsystem/src/main/res/values/appearances.xml
Labels: 🐞Fix, 💪개발자_노균욱
