Repository depromeet/SPOT-Android, pull requests merged in 2024-08, with the labels that each got.

#58 [FEAT] StatusBar 유틸 클래스 구현 및 적용
  presentation/src/main/java/com/depromeet/presentation/seatReview/ReviewActivity.kt
  presentation/src/main/java/com/depromeet/presentation/util/Utils.kt
Labels: 🎇Feature, 🦖개발자_조관희

#53 [FEAT] Setting 뷰 구현
  app/src/main/AndroidManifest.xml
  buildSrc/build/kotlin/buildSrcjar-classes.txt
  core/designsystem/src/main/res/drawable/layer_list_arrow_circle_right_20.xml
  data/src/main/java/com/depromeet/data/datasource/SignupRemoteDataSource.kt
  data/src/main/java/com/depromeet/data/datasource/remote/SignupRemoteDataSourceImpl.kt
  data/src/main/java/com/depromeet/data/remote/SignupService.kt
  data/src/main/java/com/depromeet/data/repository/SignupRepositoryImpl.kt
  domain/src/main/java/com/depromeet/domain/repository/SignupRepository.kt
  presentation/src/main/java/com/depromeet/presentation/login/ui/SignUpActivity.kt
  presentation/src/main/java/com/depromeet/presentation/setting/LoginInfoFragment.kt
  presentation/src/main/java/com/depromeet/presentation/setting/SettingActivity.kt
  presentation/src/main/java/com/depromeet/presentation/setting/SettingViewModel.kt
  presentation/src/main/java/com/depromeet/presentation/setting/TermsFragment.kt
  presentation/src/main/res/drawable/ic_arrow_circle_right.xml
  presentation/src/main/res/drawable/ic_setting_title_image.png
  presentation/src/main/res/layout/activity_setting.xml
  presentation/src/main/res/layout/fragment_login_info.xml
  presentation/src/main/res/layout/fragment_terms.xml
  presentation/src/main/res/values/strings.xml
Labels: 🎇Feature, 🍽개발자_윤성식

#60 [FEAT] release jks 셋팅
  app/build.gradle.kts
Labels: 🎇Feature, 🦖개발자_조관희

#65 [FEAT] 팀 선택화면 및 설정화면 보완
  app/src/main/AndroidManifest.xml
  buildSrc/build/kotlin/buildSrcjar-classes.txt
  buildSrc/build/kotlin/compileKotlin/cacheable/last-build.bin
  buildSrc/build/kotlin/compileKotlin/local-state/build-history.bin
  buildSrc/build/libs/buildSrc.jar
  core/designsystem/src/main/res/drawable/rect_background_white_fill_24.xml
  data/src/main/java/com/depromeet/data/intercepter/AuthInterceptor.kt
  presentation/src/main/java/com/depromeet/presentation/home/HomeActivity.kt
  presentation/src/main/java/com/depromeet/presentation/login/ui/KakaoSignupActivity.kt
  presentation/src/main/java/com/depromeet/presentation/login/ui/NicknameInputActivity.kt
  presentation/src/main/java/com/depromeet/presentation/login/ui/SignUpActivity.kt
  presentation/src/main/java/com/depromeet/presentation/login/ui/TeamSelectActivity.kt
  presentation/src/main/java/com/depromeet/presentation/login/ui/TeamSelectFragment.kt
  presentation/src/main/java/com/depromeet/presentation/login/viewmodel/KakaoSignupViewModel.kt
  presentation/src/main/java/com/depromeet/presentation/login/viewmodel/NicknameInputViewModel.kt
  presentation/src/main/java/com/depromeet/presentation/login/viewmodel/SignUpViewModel.kt
  presentation/src/main/java/com/depromeet/presentation/setting/LoginInfoFragment.kt
  presentation/src/main/java/com/depromeet/presentation/setting/LogoutDialog.kt
  presentation/src/main/java/com/depromeet/presentation/setting/SettingActivity.kt
  presentation/src/main/java/com/depromeet/presentation/setting/SettingViewModel.kt
  presentation/src/main/java/com/depromeet/presentation/setting/WithdrawDialog.kt
  presentation/src/main/res/layout/activity_setting.xml
  presentation/src/main/res/layout/fragment_logout_dialog.xml
  presentation/src/main/res/layout/fragment_team_select.xml
  presentation/src/main/res/layout/fragment_withdraw_dialog.xml
Labels: 🎇Feature, 🍽개발자_윤성식

#68 [FEAT] 시야 찾기 1차 QA
  app/src/main/res/values/themes.xml
  core/designsystem/src/main/res/drawable/rect_white_fill_4.xml
  core/designsystem/src/main/res/layout/spot_appbar.xml
  core/designsystem/src/main/res/layout/spot_team_label.xml
  domain/src/main/java/com/depromeet/domain/entity/response/viewfinder/BlockReviewResponse.kt
  domain/src/main/java/com/depromeet/domain/entity/response/viewfinder/BlockRowResponse.kt
  domain/src/main/java/com/depromeet/domain/model/viewfinder/Seat.kt
  presentation/src/main/java/com/depromeet/presentation/seatrecord/SeatRecordActivity.kt
  presentation/src/main/java/com/depromeet/presentation/seatrecord/adapter/DetailRecordAdapter.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/StadiumActivity.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/StadiumSelectionActivity.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/adapter/StadiumSelectionAdapter.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/compose/CustomTooltip.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/compose/KeywordFlowRow.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/compose/StadiumAreaText.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/compose/StadiumDetailScreen.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/compose/StadiumHeaderContent.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/compose/StadiumKeywordContent.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/compose/StadiumKeywordRow.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/compose/StadiumPictureViewPager.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/compose/StadiumReviewContent.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/compose/detailpicture/StadiumDetailReviewViewPager.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/dialog/StadiumSelectSeatDialog.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/viewmodel/StadiumDetailViewModel.kt
  presentation/src/main/res/drawable/ic_default_profile.png
  presentation/src/main/res/layout/activity_stadium.xml
  presentation/src/main/res/layout/activity_stadium_selection.xml
  presentation/src/main/res/layout/item_stadium_selection.xml
  presentation/src/main/res/values/strings.xml
Labels: 🎇Feature, 🦖개발자_조관희

#69 [feat/#64] 닉네임 shared 저장 로직 수정
  data/src/main/java/com/depromeet/data/preference/SharedPreference.kt
  domain/src/main/java/com/depromeet/domain/preference/NetworkPreference.kt
  presentation/src/main/java/com/depromeet/presentation/login/viewmodel/SignUpViewModel.kt
  presentation/src/main/java/com/depromeet/presentation/setting/LoginInfoFragment.kt
  presentation/src/main/res/layout/fragment_login_info.xml
Labels: 🐞Fix, 🍽개발자_윤성식

#70 [FEATURE] 환경설정 1차 GUI 설정
  app/src/main/AndroidManifest.xml
  app/src/main/res/values/strings.xml
  buildSrc/build/kotlin/buildSrcjar-classes.txt
  buildSrc/build/kotlin/compileKotlin/cacheable/last-build.bin
  buildSrc/build/kotlin/compileKotlin/local-state/build-history.bin
  buildSrc/build/libs/buildSrc.jar
  core/designsystem/src/main/java/com/depromeet/designsystem/SpotImageSnackBar.kt
  core/designsystem/src/main/res/values/appearances.xml
  data/src/main/java/com/depromeet/data/datasource/HomeDataSource.kt
  data/src/main/java/com/depromeet/data/datasource/remote/HomeDataSourceImpl.kt
  data/src/main/java/com/depromeet/data/intercepter/AuthInterceptor.kt
  data/src/main/java/com/depromeet/data/model/response/home/ResponseLevelUpInfoDto.kt
  data/src/main/java/com/depromeet/data/preference/SharedPreference.kt
  data/src/main/java/com/depromeet/data/remote/HomeApiService.kt
  data/src/main/java/com/depromeet/data/repository/HomeRepositoryImpl.kt
  domain/src/main/java/com/depromeet/domain/entity/response/home/LevelUpInfoResponse.kt
  domain/src/main/java/com/depromeet/domain/preference/NetworkPreference.kt
  domain/src/main/java/com/depromeet/domain/repository/HomeRepository.kt
  presentation/src/main/java/com/depromeet/presentation/home/HomeActivity.kt
  presentation/src/main/java/com/depromeet/presentation/home/LevelUpDialog.kt
  presentation/src/main/java/com/depromeet/presentation/home/adapter/LevelDescriptionAdapter.kt
  presentation/src/main/java/com/depromeet/presentation/home/viewmodel/HomeGuiViewModel.kt
  presentation/src/main/java/com/depromeet/presentation/home/viewmodel/HomeViewModel.kt
  presentation/src/main/java/com/depromeet/presentation/seatrecord/SeatRecordActivity.kt
  presentation/src/main/java/com/depromeet/presentation/seatrecord/adapter/RecentRecordAdapter.kt
  presentation/src/main/res/drawable/rect_action_enabled_line_background_secondary_fill_20.xml
  presentation/src/main/res/drawable/sel_year_drop_down.xml
  presentation/src/main/res/layout/activity_home.xml
  presentation/src/main/res/layout/activity_seat_record.xml
  presentation/src/main/res/layout/fragment_levelup_dialog.xml
  presentation/src/main/res/layout/item_level_description.xml
  presentation/src/main/res/layout/item_recent_record.xml
  presentation/src/main/res/layout/item_stadium_small_selection.xml
  presentation/src/main/res/values/strings.xml
Labels: 🎇Feature, 💪개발자_노균욱

#75 [REFACTOR] 시야 찾기 코드 리펙토링
  data/src/main/java/com/depromeet/data/datasource/ViewfinderDataSource.kt
  data/src/main/java/com/depromeet/data/datasource/remote/ViewfinderDataSourceImpl.kt
  data/src/main/java/com/depromeet/data/mapper/ViewfinderMapper.kt
  data/src/main/java/com/depromeet/data/model/request/viewfinder/BlockReviewRequestQueryDto.kt
  data/src/main/java/com/depromeet/data/model/request/viewfinder/RequestBlockReviewQueryDto.kt
  data/src/main/java/com/depromeet/data/model/response/viewfinder/BlockReviewResponseDto.kt
  data/src/main/java/com/depromeet/data/model/response/viewfinder/BlockRowResponseDto.kt
  data/src/main/java/com/depromeet/data/model/response/viewfinder/ResponseBlockReviewDto.kt
  data/src/main/java/com/depromeet/data/model/response/viewfinder/ResponseBlockRowDto.kt
  data/src/main/java/com/depromeet/data/model/response/viewfinder/ResponseStadiumDto.kt
  data/src/main/java/com/depromeet/data/model/response/viewfinder/ResponseStadiumsDto.kt
  data/src/main/java/com/depromeet/data/remote/ViewfinderService.kt
  data/src/main/java/com/depromeet/data/repository/ViewfinderRepositoryImpl.kt
  domain/src/main/java/com/depromeet/domain/entity/request/viewfinder/RequestBlockReviewQuery.kt
  domain/src/main/java/com/depromeet/domain/entity/response/viewfinder/ResponseBlockReview.kt
  domain/src/main/java/com/depromeet/domain/entity/response/viewfinder/ResponseBlockRow.kt
  domain/src/main/java/com/depromeet/domain/entity/response/viewfinder/ResponseStadium.kt
  domain/src/main/java/com/depromeet/domain/entity/response/viewfinder/ResponseStadiums.kt
  domain/src/main/java/com/depromeet/domain/repository/ViewfinderRepository.kt
  presentation/src/main/java/com/depromeet/presentation/home/HomeActivity.kt
  presentation/src/main/java/com/depromeet/presentation/home/adapter/StadiumAdapter.kt
  presentation/src/main/java/com/depromeet/presentation/home/viewmodel/HomeGuiViewModel.kt
  presentation/src/main/java/com/depromeet/presentation/mapper/KeywordMapper.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/StadiumActivity.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/StadiumDetailActivity.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/StadiumSelectionActivity.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/adapter/StadiumSelectionAdapter.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/compose/CustomTooltip.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/compose/StadiumDetailScreen.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/compose/StadiumHeaderContent.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/compose/StadiumKeywordContent.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/compose/StadiumKeywordRow.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/compose/StadiumPictureViewPager.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/compose/StadiumReviewContent.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/compose/StadiumSeatCheckBox.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/compose/StadiumViewReviewHeader.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/compose/detailpicture/StadiumDetailPictureViewPager.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/compose/detailpicture/StadiumDetailReviewViewPager.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/uistate/StadiumDetailUiState.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/viewholder/StadiumSelectionViewHolder.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/viewmodel/StadiumDetailViewModel.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/viewmodel/StadiumSelectionViewModel.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/viewmodel/StadiumViewModel.kt
Labels: 🎨Refactor, 🦖개발자_조관희

#77 [FEAT/#76] Build Variants 설정
  app/build.gradle.kts
  app/src/main/java/com/depromeet/spot/di/RetrofitModule.kt
  buildSrc/build/kotlin/buildSrcjar-classes.txt
  buildSrc/build/kotlin/compileKotlin/cacheable/last-build.bin
  buildSrc/build/kotlin/compileKotlin/local-state/build-history.bin
  buildSrc/build/libs/buildSrc.jar
  data/build.gradle.kts
  data/src/main/java/com/depromeet/data/intercepter/AuthInterceptor.kt
Labels: 🎇Feature, 💪개발자_노균욱, 🦔개발자_박민주, 🦖개발자_조관희, 🍽개발자_윤성식

#80 [BSVR-192/FIX] 시야찾기 1차 MVP 2차 QA
  app/src/main/res/values/themes.xml
  core/designsystem/src/main/java/com/depromeet/designsystem/compose/ui/SpotColor.kt
  core/designsystem/src/main/res/drawable/rect_background_white_top_24.xml
  core/designsystem/src/main/res/values/colors.xml
  domain/src/main/java/com/depromeet/domain/entity/response/viewfinder/ResponseBlockRow.kt
  presentation/src/main/java/com/depromeet/presentation/seatReview/ReviewActivity.kt
  presentation/src/main/java/com/depromeet/presentation/util/Utils.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/StadiumActivity.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/StadiumDetailActivity.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/StadiumDetailPictureFragment.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/compose/CustomTooltip.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/compose/KeywordFlowRow.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/compose/StadiumDetailScreen.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/compose/StadiumKeywordContent.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/compose/StadiumReviewContent.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/compose/detailpicture/DetailBackgroundLayer.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/compose/detailpicture/DetailCotentLayer.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/compose/detailpicture/DetailGradientLayer.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/compose/detailpicture/DetailViewPagerLayer.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/compose/detailpicture/GradientBox.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/compose/detailpicture/StadiumDetailPictureScreen.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/compose/detailpicture/StadiumDetailPictureViewPager.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/compose/detailpicture/StadiumDetailReviewViewPager.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/dialog/ReportDialog.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/dialog/StadiumFilterMonthsDialog.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/dialog/StadiumSelectSeatDialog.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/viewmodel/StadiumDetailViewModel.kt
  presentation/src/main/res/layout/activity_stadium.xml
  presentation/src/main/res/layout/fragment_report_dialog.xml
  presentation/src/main/res/layout/fragment_stadium_filter_months_dialog.xml
  presentation/src/main/res/layout/fragment_stadium_select_seat_dialog.xml
  presentation/src/main/res/values/strings.xml
  presentation/src/main/res/values/themes.xml
Labels: 🎇Feature, 🐞Fix, 🦖개발자_조관희

#82 [BSVR-201/FIX] 온보딩 화면 리팩토링 및 버그수정
  buildSrc/build/kotlin/buildSrcjar-classes.txt
  buildSrc/build/kotlin/compileKotlin/cacheable/last-build.bin
  buildSrc/build/kotlin/compileKotlin/local-state/build-history.bin
  buildSrc/build/libs/buildSrc.jar
  data/src/main/java/com/depromeet/data/model/request/signup/RequestPostSignupDto.kt
  presentation/src/main/java/com/depromeet/presentation/login/ui/KakaoSignupActivity.kt
  presentation/src/main/java/com/depromeet/presentation/login/ui/SignUpActivity.kt
  presentation/src/main/java/com/depromeet/presentation/login/ui/SignUpCompleteActivity.kt
  presentation/src/main/java/com/depromeet/presentation/login/ui/TeamSelectActivity.kt
  presentation/src/main/java/com/depromeet/presentation/login/ui/compose/KakaoSignupScreen.kt
  presentation/src/main/java/com/depromeet/presentation/login/viewmodel/KakaoSignupViewModel.kt
  presentation/src/main/res/drawable/ic_splash_big_logo.png
  presentation/src/main/res/drawable/ic_spot_big_logo.png
  presentation/src/main/res/drawable/indicator.xml
  presentation/src/main/res/layout/activity_signup.xml
  presentation/src/main/res/layout/fragment_kakao_signup.xml
  presentation/src/main/res/layout/fragment_nickname_input.xml
  presentation/src/main/res/layout/fragment_team_select.xml
Labels: 🎨Refactor, 🐞Fix, 🍽개발자_윤성식

#89 [FIX] 시야찾기 3차 QA
  domain/src/main/java/com/depromeet/domain/entity/response/viewfinder/ResponseBlockReview.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/compose/detailpicture/DetailCotentLayer.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/compose/detailpicture/StadiumDetailPictureViewPager.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/dialog/StadiumSelectSeatDialog.kt
  presentation/src/main/java/com/depromeet/presentation/viewfinder/viewmodel/StadiumDetailViewModel.kt
Labels: 🐞Fix, 🦖개발자_조관희

#92 [FIX] 홈, 시야아카이빙 2차 QA
  core/designsystem/src/main/res/drawable/ic_cheer_all_teams.png
  data/src/main/java/com/depromeet/data/model/response/home/ResponseMySeatRecordDto.kt
  domain/src/main/java/com/depromeet/domain/entity/response/home/ResponseMySeatRecord.kt
  presentation/src/main/java/com/depromeet/presentation/home/HomeActivity.kt
  presentation/src/main/java/com/depromeet/presentation/home/ProfileEditActivity.kt
  presentation/src/main/java/com/depromeet/presentation/home/customview/CustomSpeechBubbleView.kt
  presentation/src/main/java/com/depromeet/presentation/seatrecord/ConfirmDeleteDialog.kt
  presentation/src/main/java/com/depromeet/presentation/seatrecord/HeaderItemDecoration.kt
  presentation/src/main/java/com/depromeet/presentation/seatrecord/SeatRecordActivity.kt
  presentation/src/main/java/com/depromeet/presentation/seatrecord/adapter/DetailRecordAdapter.kt
  presentation/src/main/java/com/depromeet/presentation/seatrecord/adapter/RecentRecordAdapter.kt
  presentation/src/main/java/com/depromeet/presentation/seatrecord/adapter/SeatRecordAdapter.kt
  presentation/src/main/java/com/depromeet/presentation/seatrecord/mockdata/RecordDetailMockData.kt
  presentation/src/main/java/com/depromeet/presentation/seatrecord/viewholder/RecordDateViewHolder.kt
  presentation/src/main/java/com/depromeet/presentation/seatrecord/viewholder/RecordProfileViewHolder.kt
  presentation/src/main/java/com/depromeet/presentation/seatrecord/viewholder/RecordReviewViewHolder.kt
  presentation/src/main/java/com/depromeet/presentation/seatrecord/viewmodel/SeatRecordViewModel.kt
  presentation/src/main/res/layout/activity_home.xml
  presentation/src/main/res/layout/activity_profile_edit.xml
  presentation/src/main/res/layout/activity_seat_record.xml
  presentation/src/main/res/layout/fragment_confirm_delete_dialog.xml
  presentation/src/main/res/layout/fragment_upload_error_dialog.xml
  presentation/src/main/res/layout/item_baseball_team.xml
  presentation/src/main/res/layout/item_record_profile.xml
  presentation/src/main/res/values/attrs.xml
  presentation/src/main/res/values/dimen.xml
Labels: 🐞Fix, 💪개발자_노균욱

#94 [FIX/#83] 시야 후기 등록뷰 2차 QA
  buildSrc/build/kotlin/buildSrcjar-classes.txt
  buildSrc/build/kotlin/compileKotlin/cacheable/last-build.bin
  buildSrc/build/kotlin/compileKotlin/local-state/build-history.bin
  buildSrc/build/libs/buildSrc.jar
  presentation/src/main/java/com/depromeet/presentation/seatreview/dialog/DatePickerDialog.kt
  presentation/src/main/java/com/depromeet/presentation/seatreview/dialog/ReviewMySeatDialog.kt
  presentation/src/main/java/com/depromeet/presentation/seatreview/dialog/SelectSeatDialog.kt
  presentation/src/main/res/layout/activity_review.xml
  presentation/src/main/res/layout/fragment_review_my_seat_bottom_sheet.xml
  presentation/src/main/res/layout/fragment_select_seat_bottom_sheet.xml
  presentation/src/main/res/layout/fragment_upload_bottom_sheet.xml
  presentation/src/main/res/values/themes.xml
Labels: 🐞Fix, 🦔개발자_박민주

#96 [FEAT] 카카오 공유하기 예시 템플릿 작성
  app/src/main/AndroidManifest.xml
  buildSrc/src/main/kotlin/Dependencies.kt
  presentation/build.gradle.kts
  presentation/src/main/java/com/depromeet/presentation/ExampleActivity.kt
  presentation/src/main/java/com/depromeet/presentation/scheme/SchemeActivity.kt
  presentation/src/main/java/com/depromeet/presentation/util/KakaoUtils.kt
  presentation/src/main/res/layout/activity_example.xml
  presentation/src/main/res/layout/activity_scheme.xml
Labels: 🎇Feature, 🦖개발자_조관희

#100 [FIX] 좌석번호 DTO 프로퍼티 타입 변경
  data/src/main/java/com/dpm/data/model/response/viewfinder/ResponseBlockReviewDto.kt
  domain/src/main/java/com/dpm/domain/entity/response/viewfinder/ResponseBlockReview.kt
Labels: 🐞Fix, 🦖개발자_조관희

#102 [FEAT] 구역 색상 추가 및 휠체어 아이콘 추가
  core/designsystem/src/main/res/drawable/ic_wheelchair.png
  core/designsystem/src/main/res/drawable/oval_exciting_blue.xml
  core/designsystem/src/main/res/drawable/oval_section_blue.xml
  core/designsystem/src/main/res/drawable/oval_section_green.xml
  core/designsystem/src/main/res/drawable/oval_section_navy.xml
  core/designsystem/src/main/res/drawable/oval_section_orange.xml
  core/designsystem/src/main/res/drawable/oval_section_premium.xml
  core/designsystem/src/main/res/drawable/oval_section_red.xml
  core/designsystem/src/main/res/drawable/oval_section_table.xml
  presentation/src/main/java/com/dpm/presentation/seatreview/adapter/SelectSeatAdapter.kt
  presentation/src/main/res/layout/item_select_seat.xml
Labels: 🎇Feature, 🦖개발자_조관희

#103 [BSVR-222/FEAT] 시야 후기 등록 2차 - 좌석 번호 예외 케이스 구현
  buildSrc/build/kotlin/buildSrcjar-classes.txt
  buildSrc/build/kotlin/compileKotlin/cacheable/last-build.bin
  buildSrc/build/kotlin/compileKotlin/local-state/build-history.bin
  buildSrc/build/libs/buildSrc.jar
  core/designsystem/src/main/res/drawable/oval_section_exciting.xml
  data/src/main/java/com/dpm/data/model/response/seatreview/ResponseStadiumSectionDto.kt
  domain/src/main/java/com/dpm/domain/entity/response/seatreview/ResponseStadiumSection.kt
  domain/src/main/java/com/dpm/domain/model/seatreview/ValidSeat.kt
  presentation/src/main/java/com/dpm/presentation/seatreview/ReviewActivity.kt
  presentation/src/main/java/com/dpm/presentation/seatreview/ReviewViewModel.kt
  presentation/src/main/java/com/dpm/presentation/seatreview/adapter/SelectSeatAdapter.kt
  presentation/src/main/java/com/dpm/presentation/seatreview/dialog/SelectSeatDialog.kt
  presentation/src/main/res/layout/activity_review.xml
  presentation/src/main/res/layout/fragment_select_seat_bottom_sheet.xml
  presentation/src/main/res/layout/item_select_seat.xml
Labels: 🎇Feature, 🦔개발자_박민주

#107 [BSVR-223/FEAT] 시야 후기 등록 TAB 이동 및 SnackBar 추가
  data/src/main/java/com/dpm/data/datasource/SeatReviewDataSource.kt
  data/src/main/java/com/dpm/data/datasource/remote/SeatReviewDataSourceImpl.kt
  data/src/main/java/com/dpm/data/model/request/seatreview/RequestSeatReviewDto.kt
  data/src/main/java/com/dpm/data/remote/SeatReviewService.kt
  data/src/main/java/com/dpm/data/repository/SeatReviewRepositoryImpl.kt
  domain/src/main/java/com/dpm/domain/entity/request/seatreview/RequestSeatReview.kt
  domain/src/main/java/com/dpm/domain/repository/SeatReviewRepository.kt
  presentation/src/main/java/com/dpm/presentation/seatreview/ReviewActivity.kt
  presentation/src/main/java/com/dpm/presentation/seatreview/ReviewViewModel.kt
  presentation/src/main/java/com/dpm/presentation/seatreview/dialog/ReviewMySeatDialog.kt
  presentation/src/main/java/com/dpm/presentation/seatreview/dialog/SelectSeatDialog.kt
  presentation/src/main/res/layout/fragment_review_my_seat_bottom_sheet.xml
  presentation/src/main/res/layout/fragment_select_seat_bottom_sheet.xml
Labels: 🎇Feature, 🦔개발자_박민주

#109 [FIX] 홈, 시야아카이빙 2차 QA(+@)
  buildSrc/build/kotlin/buildSrcjar-classes.txt
  buildSrc/build/kotlin/compileKotlin/cacheable/last-build.bin
  buildSrc/build/kotlin/compileKotlin/local-state/build-history.bin
  buildSrc/build/libs/buildSrc.jar
  core/designsystem/src/main/java/com/dpm/designsystem/SpotDropDownSpinner.kt
  core/designsystem/src/main/java/com/dpm/designsystem/SpotImageSnackBar.kt
  core/designsystem/src/main/res/drawable/ic_default_profile.xml
  core/designsystem/src/main/res/drawable/rect_59ffffff_fill_20.xml
  core/designsystem/src/main/res/drawable/rect_background_white_fill_20.xml
  core/designsystem/src/main/res/drawable/rect_background_white_fill_gray200_stroke_999.xml
  core/designsystem/src/main/res/drawable/sel_year_drop_down.xml
  core/designsystem/src/main/res/layout/spot_image_snackbar.xml
  core/designsystem/src/main/res/values/colors.xml
  data/src/main/java/com/dpm/data/datasource/remote/HomeDataSourceImpl.kt
  data/src/main/java/com/dpm/data/model/request/home/RequestMySeatRecordDto.kt
  data/src/main/java/com/dpm/data/model/response/home/ResponseMySeatRecordDto.kt
  data/src/main/java/com/dpm/data/remote/HomeApiService.kt
  domain/src/main/java/com/dpm/domain/entity/request/home/RequestMySeatRecord.kt
  domain/src/main/java/com/dpm/domain/entity/response/home/ResponseMySeatRecord.kt
  presentation/src/main/java/com/dpm/presentation/extension/ViewExt.kt
  presentation/src/main/java/com/dpm/presentation/home/HomeActivity.kt
  presentation/src/main/java/com/dpm/presentation/home/ProfileEditActivity.kt
  presentation/src/main/java/com/dpm/presentation/home/dialog/LevelDescriptionDialog.kt
  presentation/src/main/java/com/dpm/presentation/home/dialog/LevelUpDialog.kt
  presentation/src/main/java/com/dpm/presentation/home/dialog/ProfileDeleteConfirmDialog.kt
  presentation/src/main/java/com/dpm/presentation/home/dialog/ProfileImageUploadDialog.kt
  presentation/src/main/java/com/dpm/presentation/home/dialog/UploadErrorDialog.kt
  presentation/src/main/java/com/dpm/presentation/seatrecord/SeatDetailRecordFragment.kt
  presentation/src/main/java/com/dpm/presentation/seatrecord/SeatRecordActivity.kt
  presentation/src/main/java/com/dpm/presentation/seatrecord/TempSeatRecordActivity.kt
  presentation/src/main/java/com/dpm/presentation/seatrecord/dialog/ConfirmDeleteDialog.kt
  presentation/src/main/java/com/dpm/presentation/seatrecord/dialog/EditDatePickerDialog.kt
  presentation/src/main/java/com/dpm/presentation/seatrecord/dialog/RecordEditDialog.kt
  presentation/src/main/java/com/dpm/presentation/seatrecord/paging/SeatRecordPagingSource.kt
  presentation/src/main/java/com/dpm/presentation/seatrecord/viewholder/RecordProfileViewHolder.kt
  presentation/src/main/java/com/dpm/presentation/seatrecord/viewmodel/SeatRecordViewModel.kt
  presentation/src/main/java/com/dpm/presentation/seatreview/dialog/ImageUploadDialog.kt
  presentation/src/main/res/drawable/circle_gray50_fill_gray200_stroke.xml
  presentation/src/main/res/layout/activity_home.xml
  presentation/src/main/res/layout/activity_profile_edit.xml
  presentation/src/main/res/layout/activity_seat_record.xml
  presentation/src/main/res/layout/item_baseball_team.xml
  presentation/src/main/res/layout/item_recent_month.xml
  presentation/src/main/res/layout/item_recent_record.xml
  presentation/src/main/res/layout/item_record_profile.xml
  presentation/src/main/res/layout/item_record_review.xml
  presentation/src/main/res/layout/item_seat_review_detail.xml
  presentation/src/main/res/layout/item_stadium_search.xml
Labels: 🐞Fix, 💪개발자_노균욱

#111 [FEAUTRE] 스크랩 화면(상세화면X) UI 1차구현
  app/src/main/AndroidManifest.xml
  buildSrc/build/kotlin/compileKotlin/cacheable/last-build.bin
  buildSrc/build/kotlin/compileKotlin/local-state/build-history.bin
  buildSrc/build/libs/buildSrc.jar
  core/designsystem/src/main/res/drawable/ic_bookmark.xml
  core/designsystem/src/main/res/drawable/ic_settings2.xml
  core/designsystem/src/main/res/drawable/rect_background_tertiary_fill_999.xml
  core/designsystem/src/main/res/drawable/rect_foreground_white_fill_top_8.xml
  core/designsystem/src/main/res/drawable/rect_spot_green_line_background_white_fill_999.xml
  core/designsystem/src/main/res/drawable/rect_stroke_tertiary_line_background_white_fill_999.xml
  presentation/src/main/java/com/dpm/presentation/scrap/ScrapActivity.kt
  presentation/src/main/java/com/dpm/presentation/scrap/adapter/ScrapFilterAdapter.kt
  presentation/src/main/java/com/dpm/presentation/scrap/adapter/ScrapMonthAdapter.kt
  presentation/src/main/java/com/dpm/presentation/scrap/adapter/ScrapRecordAdapter.kt
  presentation/src/main/java/com/dpm/presentation/scrap/dialog/ScrapFilterDialog.kt
  presentation/src/main/java/com/dpm/presentation/scrap/viewmodel/ScrapViewModel.kt
  presentation/src/main/res/layout/activity_scrap.xml
  presentation/src/main/res/layout/fragment_scrap_detail.xml
  presentation/src/main/res/layout/fragment_scrap_filter_dialog.xml
  presentation/src/main/res/layout/item_scrap_filter.xml
  presentation/src/main/res/layout/item_scrap_filter_selected.xml
  presentation/src/main/res/layout/item_scrap_month.xml
  presentation/src/main/res/layout/item_scrap_record.xml
  presentation/src/main/res/values/strings.xml
Labels: 🎇Feature, 💪개발자_노균욱

#113 [fix/#105] 온보딩, 설정화면 UI 수정 및 이미지 교체
  buildSrc/build/kotlin/buildSrcjar-classes.txt
  buildSrc/build/kotlin/compileKotlin/cacheable/last-build.bin
  buildSrc/build/kotlin/compileKotlin/local-state/build-history.bin
  buildSrc/build/libs/buildSrc.jar
  core/designsystem/src/main/res/drawable/ic_edittext_close.xml
  core/designsystem/src/main/res/drawable/ic_setting_my_page.xml
  core/designsystem/src/main/res/drawable/ic_setting_to_link.xml
  core/designsystem/src/main/res/drawable/ic_signup_image_1.png
  core/designsystem/src/main/res/drawable/ic_signup_image_2.png
  core/designsystem/src/main/res/drawable/ic_signup_image_3.png
  core/designsystem/src/main/res/drawable/ic_signup_image_4.png
  core/designsystem/src/main/res/drawable/ic_signup_success.png
  presentation/src/main/java/com/dpm/presentation/login/ui/NicknameInputActivity.kt
  presentation/src/main/java/com/dpm/presentation/login/ui/SignUpActivity.kt
  presentation/src/main/java/com/dpm/presentation/login/ui/SignUpCompleteActivity.kt
  presentation/src/main/java/com/dpm/presentation/login/ui/TeamSelectActivity.kt
  presentation/src/main/java/com/dpm/presentation/login/ui/compose/KakaoSignupScreen.kt
  presentation/src/main/java/com/dpm/presentation/login/viewmodel/NicknameInputViewModel.kt
  presentation/src/main/java/com/dpm/presentation/login/viewmodel/SignUpViewModel.kt
  presentation/src/main/java/com/dpm/presentation/setting/LoginInfoFragment.kt
  presentation/src/main/java/com/dpm/presentation/setting/SettingActivity.kt
  presentation/src/main/java/com/dpm/presentation/setting/TermsFragment.kt
  presentation/src/main/java/com/dpm/presentation/util/ComposableUtils.kt
  presentation/src/main/res/drawable/ic_signup_complete.png
  presentation/src/main/res/drawable/ic_signup_image_1.png
  presentation/src/main/res/drawable/ic_signup_image_2.png
  presentation/src/main/res/drawable/ic_signup_image_3.png
  presentation/src/main/res/layout/activity_setting.xml
  presentation/src/main/res/layout/activity_signup_complete.xml
  presentation/src/main/res/layout/fragment_login_info.xml
  presentation/src/main/res/layout/fragment_nickname_input.xml
  presentation/src/main/res/layout/fragment_team_select.xml
  presentation/src/main/res/layout/fragment_terms.xml
Labels: 🐞Fix, 🍽개발자_윤성식

#115 [FEAT] 시야 찾기 2차 MVP 구현 V2
  core/designsystem/src/main/java/com/dpm/designsystem/SpotSnackBar.kt
  core/designsystem/src/main/res/drawable/rect_body_subtitle_fill_60.xml
  core/designsystem/src/main/res/layout/spot_snackbar.xml
  data/src/main/java/com/dpm/data/datasource/ViewfinderDataSource.kt
  data/src/main/java/com/dpm/data/datasource/remote/ViewfinderDataSourceImpl.kt
  data/src/main/java/com/dpm/data/model/response/viewfinder/ResponseBlockReviewDto.kt
  data/src/main/java/com/dpm/data/preference/SharedPreference.kt
  data/src/main/java/com/dpm/data/remote/ViewfinderService.kt
  data/src/main/java/com/dpm/data/repository/ViewfinderRepositoryImpl.kt
  domain/src/main/java/com/dpm/domain/entity/response/viewfinder/ResponseBlockReview.kt
  domain/src/main/java/com/dpm/domain/preference/NetworkPreference.kt
  domain/src/main/java/com/dpm/domain/repository/ViewfinderRepository.kt
  presentation/src/main/java/com/dpm/presentation/util/KakaoUtils.kt
  presentation/src/main/java/com/dpm/presentation/util/StadiumUxWritingUtils.kt
  presentation/src/main/java/com/dpm/presentation/viewfinder/StadiumDetailActivity.kt
  presentation/src/main/java/com/dpm/presentation/viewfinder/StadiumDetailPictureFragment.kt
  presentation/src/main/java/com/dpm/presentation/viewfinder/compose/LikeButton.kt
  presentation/src/main/java/com/dpm/presentation/viewfinder/compose/ReviewContentBottom.kt
  presentation/src/main/java/com/dpm/presentation/viewfinder/compose/StadiumDetailScreen.kt
  presentation/src/main/java/com/dpm/presentation/viewfinder/compose/StadiumHeaderContent.kt
  presentation/src/main/java/com/dpm/presentation/viewfinder/compose/StadiumPictureViewPager.kt
  presentation/src/main/java/com/dpm/presentation/viewfinder/compose/StadiumReviewContent.kt
  presentation/src/main/java/com/dpm/presentation/viewfinder/compose/detailpicture/DetailCotentLayer.kt
  presentation/src/main/java/com/dpm/presentation/viewfinder/compose/detailpicture/DetailReviewInteractionItems.kt
  presentation/src/main/java/com/dpm/presentation/viewfinder/compose/detailpicture/DetailViewPagerLayer.kt
  presentation/src/main/java/com/dpm/presentation/viewfinder/compose/detailpicture/LikeTooltip.kt
  presentation/src/main/java/com/dpm/presentation/viewfinder/compose/detailpicture/StadiumDetailPictureScreen.kt
  presentation/src/main/java/com/dpm/presentation/viewfinder/compose/detailpicture/StadiumDetailPictureViewPager.kt
  presentation/src/main/java/com/dpm/presentation/viewfinder/compose/detailpicture/StadiumDetailReviewViewPager.kt
  presentation/src/main/java/com/dpm/presentation/viewfinder/compose/detailpicture/main/StadiumDetailPictureTopScreen.kt
  presentation/src/main/java/com/dpm/presentation/viewfinder/compose/detailpicture/top/StadiumDetailPictureMainScreen.kt
  presentation/src/main/java/com/dpm/presentation/viewfinder/uistate/StadiumDetailUiState.kt
  presentation/src/main/java/com/dpm/presentation/viewfinder/viewmodel/StadiumDetailViewModel.kt
  presentation/src/main/res/values/strings.xml
Labels: 🎇Feature, 🦖개발자_조관희

#119 [FEAT] 카카오 공유하기 딥링크 구현
  app/src/main/java/com/dpm/spot/di/DataSourceModule.kt
  app/src/main/java/com/dpm/spot/di/RepositoryModule.kt
  buildSrc/src/main/kotlin/Dependencies.kt
  data/src/main/java/com/dpm/data/datasource/AuthDataSource.kt
  data/src/main/java/com/dpm/data/datasource/local/AuthDataSourceImpl.kt
  data/src/main/java/com/dpm/data/repository/AuthRepositoryImpl.kt
  domain/build.gradle.kts
  domain/src/main/java/com/dpm/domain/repository/AuthRepository.kt
  domain/src/main/java/com/dpm/domain/usecase/GetTokenUseCase.kt
  presentation/src/main/java/com/dpm/presentation/home/HomeActivity.kt
  presentation/src/main/java/com/dpm/presentation/login/ui/KakaoSignupActivity.kt
  presentation/src/main/java/com/dpm/presentation/login/ui/NicknameInputActivity.kt
  presentation/src/main/java/com/dpm/presentation/login/ui/SignUpActivity.kt
  presentation/src/main/java/com/dpm/presentation/login/ui/SignUpCompleteActivity.kt
  presentation/src/main/java/com/dpm/presentation/login/ui/TeamSelectActivity.kt
  presentation/src/main/java/com/dpm/presentation/scheme/SchemeActivity.kt
  presentation/src/main/java/com/dpm/presentation/scheme/viewmodel/SchemeViewModel.kt
  presentation/src/main/java/com/dpm/presentation/viewfinder/StadiumActivity.kt
  presentation/src/main/java/com/dpm/presentation/viewfinder/StadiumDetailActivity.kt
  presentation/src/main/java/com/dpm/presentation/viewfinder/compose/StadiumDetailScreen.kt
  presentation/src/main/java/com/dpm/presentation/viewfinder/compose/detailpicture/main/StadiumDetailPictureTopScreen.kt
  presentation/src/main/java/com/dpm/presentation/viewfinder/compose/detailpicture/top/StadiumDetailPictureMainScreen.kt
  presentation/src/main/java/com/dpm/presentation/viewfinder/viewmodel/StadiumDetailViewModel.kt
Labels: 🎇Feature, 🦖개발자_조관희

#120 [FEAT] 홈, 시야아카이빙 2차 MVP 화면 구현
  buildSrc/build/kotlin/compileKotlin/cacheable/last-build.bin
  buildSrc/build/kotlin/compileKotlin/local-state/build-history.bin
  buildSrc/build/libs/buildSrc.jar
  core/designsystem/src/main/res/drawable/ic_scrap_active.xml
  core/designsystem/src/main/res/drawable/ic_scrap_inactive.xml
  presentation/src/main/java/com/dpm/presentation/home/HomeActivity.kt
  presentation/src/main/java/com/dpm/presentation/home/ProfileEditActivity.kt
  presentation/src/main/java/com/dpm/presentation/home/customview/CustomSpeechBubbleView.kt
  presentation/src/main/java/com/dpm/presentation/seatrecord/HeaderItemDecoration.kt
  presentation/src/main/java/com/dpm/presentation/seatrecord/SeatDetailRecordFragment.kt
  presentation/src/main/java/com/dpm/presentation/seatrecord/SeatRecordActivity.kt
  presentation/src/main/java/com/dpm/presentation/seatrecord/TempSeatRecordActivity.kt
  presentation/src/main/java/com/dpm/presentation/seatrecord/TestSeatRecordActivity.kt
  presentation/src/main/java/com/dpm/presentation/seatrecord/adapter/DetailRecordAdapter.kt
  presentation/src/main/java/com/dpm/presentation/seatrecord/adapter/MonthRecordAdapter.kt
  presentation/src/main/java/com/dpm/presentation/seatrecord/adapter/RecentRecordAdapter.kt
  presentation/src/main/java/com/dpm/presentation/seatrecord/adapter/SeatRecordAdapter.kt
  presentation/src/main/java/com/dpm/presentation/seatrecord/dialog/ConfirmDeleteDialog.kt
  presentation/src/main/java/com/dpm/presentation/seatrecord/viewholder/RecordProfileViewHolder.kt
  presentation/src/main/java/com/dpm/presentation/seatrecord/viewholder/RecordReviewViewHolder.kt
  presentation/src/main/java/com/dpm/presentation/seatrecord/viewholder/RecordSelectSeatViewHolder.kt
  presentation/src/main/java/com/dpm/presentation/seatrecord/viewmodel/SeatRecordViewModel.kt
  presentation/src/main/res/drawable/rect_body_subtitle_fill_1.xml
  presentation/src/main/res/drawable/rect_error_primary_stroke_35.xml
  presentation/src/main/res/drawable/rect_stroke_positive_primary_stroke_35.xml
  presentation/src/main/res/layout/activity_home.xml
  presentation/src/main/res/layout/activity_profile_edit.xml
  presentation/src/main/res/layout/activity_seat_record.xml
  presentation/src/main/res/layout/activity_temp_seat_record.xml
  presentation/src/main/res/layout/activity_test_seat_record.xml
  presentation/src/main/res/layout/item_baseball_team.xml
  presentation/src/main/res/layout/item_recent_record.xml
  presentation/src/main/res/layout/item_record_profile.xml
  presentation/src/main/res/layout/item_record_select_review.xml
  presentation/src/main/res/layout/item_seat_review_detail.xml
  presentation/src/main/res/values/attrs.xml
  presentation/src/main/res/values/strings.xml
Labels: 🎇Feature, 💪개발자_노균욱

#121 [FEAT] Compose 커스텀 갤러리 구현
  app/src/main/AndroidManifest.xml
  core/designsystem/src/main/res/drawable/ic_image_selected.xml
  presentation/build.gradle.kts
  presentation/src/main/java/com/dpm/presentation/gallery/GalleryActivity.kt
  presentation/src/main/java/com/dpm/presentation/gallery/GalleryScreen.kt
  presentation/src/main/java/com/dpm/presentation/home/dialog/ProfileImageUploadDialog.kt
  presentation/src/main/java/com/dpm/presentation/seatreview/ReviewActivity.kt
  presentation/src/main/java/com/dpm/presentation/seatreview/dialog/main/ImageUploadDialog.kt
  presentation/src/main/java/com/dpm/presentation/util/ComposableUtils.kt
  presentation/src/main/java/com/dpm/presentation/util/ScreenType.kt
  presentation/src/main/res/layout/activity_gallery.xml
Labels: 🎇Feature, 🍽개발자_윤성식

#124 [FEAT] 로티 추가 및 직관 등록 API 수정
  data/src/main/java/com/dpm/data/datasource/SeatReviewDataSource.kt
  data/src/main/java/com/dpm/data/datasource/remote/SeatReviewDataSourceImpl.kt
  data/src/main/java/com/dpm/data/model/response/seatreview/ResponseSeatReviewDto.kt
  data/src/main/java/com/dpm/data/remote/SeatReviewService.kt
  data/src/main/java/com/dpm/data/repository/SeatReviewRepositoryImpl.kt
  domain/src/main/java/com/dpm/domain/entity/response/seatreview/ResponseSeatReview.kt
  domain/src/main/java/com/dpm/domain/repository/SeatReviewRepository.kt
  presentation/src/main/java/com/dpm/presentation/home/HomeActivity.kt
  presentation/src/main/java/com/dpm/presentation/seatreview/ReviewActivity.kt
  presentation/src/main/java/com/dpm/presentation/seatreview/SelectViewImageActivity.kt
  presentation/src/main/java/com/dpm/presentation/seatreview/dialog/view/SeatShareDialog.kt
  presentation/src/main/java/com/dpm/presentation/seatreview/dialog/view/ViewUploadDialog.kt
  presentation/src/main/java/com/dpm/presentation/seatreview/sample/ReviewData.kt
  presentation/src/main/java/com/dpm/presentation/seatreview/viewmodel/ReviewViewModel.kt
  presentation/src/main/res/drawable/ic_circle_delete_image.xml
  presentation/src/main/res/drawable/rect_background_tertiary_fill_32.xml
  presentation/src/main/res/layout/activity_review.xml
  presentation/src/main/res/layout/activity_select_view_image.xml
  presentation/src/main/res/layout/fragment_feed_upload_dialog.xml
  presentation/src/main/res/layout/fragment_select_seat_bottom_sheet.xml
  presentation/src/main/res/layout/fragment_sight_share_bottom_sheet.xml
  presentation/src/main/res/layout/fragment_view_upload_dialog.xml
  presentation/src/main/res/raw/check.json
Labels: 🎇Feature, 🦔개발자_박민주

#127 [HOTFIX] 리뷰 등록 UI 수정 및 nickName nullable 처리
  buildSrc/build/kotlin/compileKotlin/cacheable/last-build.bin
  buildSrc/build/kotlin/compileKotlin/local-state/build-history.bin
  buildSrc/build/libs/buildSrc.jar
  data/src/main/java/com/dpm/data/model/response/viewfinder/ResponseBlockReviewDto.kt
  presentation/src/main/java/com/dpm/presentation/seatreview/ReviewActivity.kt
Labels: 🚨Hotfix, 🦔개발자_박민주

#128 [FEAT] 스크랩 2차 MVP 화면 서버통신 및 상세화면 개발
  buildSrc/build/kotlin/compileKotlin/cacheable/last-build.bin
  buildSrc/build/kotlin/compileKotlin/local-state/build-history.bin
  buildSrc/build/libs/buildSrc.jar
  core/designsystem/src/main/res/drawable/ic_scrap_inactive.xml
  core/designsystem/src/main/res/values/colors.xml
  data/src/main/java/com/dpm/data/datasource/HomeDataSource.kt
  data/src/main/java/com/dpm/data/datasource/remote/HomeDataSourceImpl.kt
  data/src/main/java/com/dpm/data/model/request/home/RequestScrapDto.kt
  data/src/main/java/com/dpm/data/model/response/home/ResponseScrapDto.kt
  data/src/main/java/com/dpm/data/remote/HomeApiService.kt
  data/src/main/java/com/dpm/data/repository/HomeRepositoryImpl.kt
  domain/src/main/java/com/dpm/domain/entity/request/home/RequestScrap.kt
  domain/src/main/java/com/dpm/domain/entity/response/home/ResponseScrap.kt
  domain/src/main/java/com/dpm/domain/repository/HomeRepository.kt
  presentation/src/main/java/com/dpm/presentation/home/HomeActivity.kt
  presentation/src/main/java/com/dpm/presentation/scrap/ScrapActivity.kt
  presentation/src/main/java/com/dpm/presentation/scrap/ScrapDetailPictureFragment.kt
  presentation/src/main/java/com/dpm/presentation/scrap/adapter/ScrapDetailAdapter.kt
  presentation/src/main/java/com/dpm/presentation/scrap/adapter/ScrapImageAdapter.kt
  presentation/src/main/java/com/dpm/presentation/scrap/adapter/ScrapRecordAdapter.kt
  presentation/src/main/java/com/dpm/presentation/scrap/viewmodel/ScrapViewModel.kt
  presentation/src/main/java/com/dpm/presentation/seatrecord/uiMapper/HomeMapper.kt
  presentation/src/main/res/drawable/circle_stroke_tertiary_stroke_1.xml
  presentation/src/main/res/drawable/indicator_selected.xml
  presentation/src/main/res/drawable/indicator_unselected.xml
  presentation/src/main/res/drawable/rect_transparentblack01_fill_80.xml
  presentation/src/main/res/layout/activity_home.xml
  presentation/src/main/res/layout/activity_scrap.xml
  presentation/src/main/res/layout/fragment_scrap_detail_picture.xml
  presentation/src/main/res/layout/item_scrap_detail.xml
  presentation/src/main/res/layout/item_scrap_image.xml
  presentation/src/main/res/layout/item_scrap_record.xml
  presentation/src/main/res/values/strings.xml
Labels: 🎇Feature, 💪개발자_노균욱

#134 [FIX] 온보딩, 설정 2차 QA
  core/designsystem/src/main/res/drawable/ic_signup_image_3.png
  core/designsystem/src/main/res/drawable/ic_signup_image_4.png
  presentation/src/main/java/com/dpm/presentation/login/ui/NicknameInputActivity.kt
  presentation/src/main/res/layout/fragment_nickname_input.xml
  presentation/src/main/res/layout/fragment_terms.xml
Labels: 🐞Fix, 🍽개발자_윤성식

#135 [FEAT] Mixpanel 세팅 및 시야(직관) 등록 이벤트 로깅
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/dpm/spot/MyApp.kt
  buildSrc/build/kotlin/compileKotlin/cacheable/last-build.bin
  buildSrc/build/kotlin/compileKotlin/local-state/build-history.bin
  buildSrc/build/libs/buildSrc.jar
  buildSrc/src/main/kotlin/Dependencies.kt
  presentation/build.gradle.kts
  presentation/src/main/java/com/dpm/presentation/seatreview/ReviewActivity.kt
  presentation/src/main/java/com/dpm/presentation/seatreview/dialog/main/ImageUploadDialog.kt
  presentation/src/main/java/com/dpm/presentation/seatreview/dialog/main/ReviewMySeatDialog.kt
  presentation/src/main/java/com/dpm/presentation/seatreview/dialog/main/SelectSeatDialog.kt
  presentation/src/main/java/com/dpm/presentation/util/MixpanelManager.kt
Labels: 🎇Feature, 🦔개발자_박민주

#137 [FEAT] 좋아요 로티 추가 및 적용
  core/designsystem/src/main/res/raw/lottie_like.json
  presentation/build.gradle.kts
  presentation/src/main/java/com/dpm/presentation/viewfinder/StadiumDetailPictureFragment.kt
  presentation/src/main/java/com/dpm/presentation/viewfinder/compose/ReviewContentBottom.kt
  presentation/src/main/java/com/dpm/presentation/viewfinder/compose/StadiumReviewContent.kt
  presentation/src/main/java/com/dpm/presentation/viewfinder/compose/detailpicture/DetailReviewInteractionItems.kt
  presentation/src/main/java/com/dpm/presentation/viewfinder/compose/detailpicture/StadiumDetailPictureScreen.kt
  presentation/src/main/java/com/dpm/presentation/viewfinder/compose/detailpicture/StadiumDetailPictureViewPager.kt
  presentation/src/main/java/com/dpm/presentation/viewfinder/compose/detailpicture/main/StadiumDetailPictureTopScreen.kt
  presentation/src/main/java/com/dpm/presentation/viewfinder/viewmodel/StadiumDetailViewModel.kt
Labels: 🎇Feature, 🦖개발자_조관희

#140 [FIX] 등록 타입 선택뷰 이미지 교체
  buildSrc/build/kotlin/compileKotlin/cacheable/last-build.bin
  buildSrc/build/kotlin/compileKotlin/local-state/build-history.bin
  buildSrc/build/libs/buildSrc.jar
  presentation/src/main/res/drawable/ic_select_type_image.xml
  presentation/src/main/res/layout/fragment_select_review_type_dialog.xml
  presentation/src/main/res/layout/fragment_select_seat_bottom_sheet.xml
Labels: 🐞Fix, 🦔개발자_박민주

#142 [FEATURE] 시야 찾기 이벤트 로깅 심기 🌴
  presentation/src/main/java/com/dpm/presentation/viewfinder/StadiumActivity.kt
  presentation/src/main/java/com/dpm/presentation/viewfinder/StadiumDetailActivity.kt
  presentation/src/main/java/com/dpm/presentation/viewfinder/StadiumDetailPictureFragment.kt
  presentation/src/main/java/com/dpm/presentation/viewfinder/StadiumSelectionActivity.kt
Labels: 🐞Fix, 🦖개발자_조관희

#145 [FIX] 디자인 배포전 일괄 수정
  presentation/src/main/java/com/dpm/presentation/scrap/adapter/ScrapDetailAdapter.kt
  presentation/src/main/java/com/dpm/presentation/seatrecord/adapter/DetailRecordAdapter.kt
  presentation/src/main/java/com/dpm/presentation/seatreview/dialog/view/SeatShareDialog.kt
  presentation/src/main/res/layout/fragment_sight_share_bottom_sheet.xml
  presentation/src/main/res/layout/item_stadium_small_selection.xml
Labels: 🐞Fix, 💪개발자_노균욱

#146 [FIX] 시야찾기 기능 QA V1
  app/src/main/java/com/dpm/spot/MyApp.kt
  buildSrc/src/main/kotlin/Constants.kt
  presentation/build.gradle.kts
  presentation/src/main/java/com/dpm/presentation/viewfinder/compose/StadiumDetailScreen.kt
  presentation/src/main/java/com/dpm/presentation/viewfinder/compose/StadiumReviewContent.kt
  presentation/src/main/java/com/dpm/presentation/viewfinder/compose/detailpicture/DetailCotentLayer.kt
  presentation/src/main/java/com/dpm/presentation/viewfinder/viewmodel/StadiumDetailViewModel.kt
Labels: 🐞Fix, 🦖개발자_조관희

#148 [FIX] 시야찾기 2차 MVP 기술 QA V2
  presentation/src/main/java/com/dpm/presentation/util/KakaoUtils.kt
  presentation/src/main/java/com/dpm/presentation/viewfinder/compose/detailpicture/DetailReviewInteractionItems.kt
  presentation/src/main/java/com/dpm/presentation/viewfinder/compose/detailpicture/DetailViewPagerLayer.kt
  presentation/src/main/java/com/dpm/presentation/viewfinder/compose/detailpicture/StadiumDetailPictureViewPager.kt
  presentation/src/main/java/com/dpm/presentation/viewfinder/compose/detailpicture/StadiumDetailReviewViewPager.kt
  presentation/src/main/java/com/dpm/presentation/viewfinder/compose/detailpicture/main/StadiumDetailPictureTopScreen.kt
  presentation/src/main/java/com/dpm/presentation/viewfinder/compose/detailpicture/top/StadiumDetailPictureMainScreen.kt
Labels: 🐞Fix, 🦖개발자_조관희

#149 [FIX] 기술적 QA 수정
  buildSrc/build/kotlin/compileKotlin/cacheable/last-build.bin
  buildSrc/build/kotlin/compileKotlin/local-state/build-history.bin
  buildSrc/build/libs/buildSrc.jar
  presentation/src/main/java/com/dpm/presentation/home/ProfileEditActivity.kt
  presentation/src/main/java/com/dpm/presentation/seatrecord/SeatRecordActivity.kt
  presentation/src/main/java/com/dpm/presentation/setting/SettingActivity.kt
  presentation/src/main/java/com/dpm/presentation/setting/SettingViewModel.kt
  presentation/src/main/res/layout/activity_seat_record.xml
Labels: 🐞Fix, 💪개발자_노균욱

#152 [FIX] 시야 찾기 2차 MVP QA V2
  core/designsystem/src/main/res/raw/lottie_like.json
  core/designsystem/src/main/res/values/appearances.xml
  presentation/src/main/assets/web/stadium.js
  presentation/src/main/java/com/dpm/presentation/util/Utils.kt
  presentation/src/main/java/com/dpm/presentation/viewfinder/StadiumActivity.kt
  presentation/src/main/java/com/dpm/presentation/viewfinder/StadiumDetailActivity.kt
  presentation/src/main/java/com/dpm/presentation/viewfinder/StadiumDetailPictureFragment.kt
  presentation/src/main/java/com/dpm/presentation/viewfinder/compose/LikeButton.kt
  presentation/src/main/java/com/dpm/presentation/viewfinder/compose/ReviewContentBottom.kt
  presentation/src/main/java/com/dpm/presentation/viewfinder/compose/StadiumDetailScreen.kt
  presentation/src/main/java/com/dpm/presentation/viewfinder/compose/StadiumReviewContent.kt
  presentation/src/main/java/com/dpm/presentation/viewfinder/compose/detailpicture/DetailViewPagerLayer.kt
  presentation/src/main/java/com/dpm/presentation/viewfinder/compose/detailpicture/LikeTooltip.kt
  presentation/src/main/java/com/dpm/presentation/viewfinder/compose/detailpicture/StadiumDetailPictureViewPager.kt
  presentation/src/main/java/com/dpm/presentation/viewfinder/compose/detailpicture/StadiumDetailReviewViewPager.kt
  presentation/src/main/java/com/dpm/presentation/viewfinder/compose/detailpicture/main/StadiumDetailPictureTopScreen.kt
  presentation/src/main/java/com/dpm/presentation/viewfinder/compose/detailpicture/top/StadiumDetailPictureMainScreen.kt
  presentation/src/main/java/com/dpm/presentation/viewfinder/viewholder/StadiumSectionRecommendViewHolder.kt
  presentation/src/main/res/layout/activity_stadium.xml
  presentation/src/main/res/layout/item_block_recommend.xml
  presentation/src/main/res/values/strings.xml
Labels: 🐞Fix, 🦖개발자_조관희

#154 [FIX] 권한 수정
  buildSrc/build/kotlin/compileKotlin/cacheable/last-build.bin
  buildSrc/build/kotlin/compileKotlin/local-state/build-history.bin
  buildSrc/build/libs/buildSrc.jar
  presentation/src/main/java/com/dpm/presentation/gallery/GalleryScreen.kt
Labels: 🐞Fix, 🍽개발자_윤성식

#158 [FIX] 시야 등록 2차 MVP 1차 QA
  buildSrc/build/kotlin/compileKotlin/cacheable/last-build.bin
  buildSrc/build/kotlin/compileKotlin/local-state/build-history.bin
  buildSrc/build/libs/buildSrc.jar
  core/designsystem/src/main/res/drawable/ic_wheel_chair.xml
  core/designsystem/src/main/res/drawable/ic_wheelchair.png
  presentation/src/main/java/com/dpm/presentation/seatreview/ReviewActivity.kt
  presentation/src/main/java/com/dpm/presentation/seatreview/adapter/SelectSeatAdapter.kt
  presentation/src/main/java/com/dpm/presentation/seatreview/dialog/ReviewTypeDialog.kt
  presentation/src/main/java/com/dpm/presentation/seatreview/dialog/main/SelectSeatDialog.kt
  presentation/src/main/java/com/dpm/presentation/seatreview/dialog/view/SeatShareDialog.kt
  presentation/src/main/java/com/dpm/presentation/seatreview/dialog/view/ViewUploadDialog.kt
  presentation/src/main/java/com/dpm/presentation/viewfinder/viewholder/StadiumSectionViewHolder.kt
  presentation/src/main/res/drawable/ic_upload_seat_view_image.xml
  presentation/src/main/res/drawable/rect_background_positive_fill_secondary_line_12.xml
  presentation/src/main/res/drawable/rect_background_secondary_fill_error_primary_line_8.xml
  presentation/src/main/res/layout/activity_review.xml
  presentation/src/main/res/layout/fragment_review_my_seat_bottom_sheet.xml
  presentation/src/main/res/layout/fragment_select_review_type_dialog.xml
  presentation/src/main/res/layout/fragment_select_seat_bottom_sheet.xml
  presentation/src/main/res/layout/item_select_seat.xml
Labels: 🐞Fix, 🦔개발자_박민주

#159 [FIX] 홈 2차 MVP 1차 QA
  buildSrc/build/kotlin/compileKotlin/cacheable/last-build.bin
  buildSrc/build/kotlin/compileKotlin/local-state/build-history.bin
  buildSrc/build/libs/buildSrc.jar
  core/designsystem/src/main/java/com/dpm/designsystem/SpotDropDownSpinner.kt
  core/designsystem/src/main/res/drawable/sel_year_drop_down_up.xml
  core/designsystem/src/main/res/layout/item_spot_spinner_dropdown.xml
  data/src/main/java/com/dpm/data/preference/SharedPreference.kt
  domain/src/main/java/com/dpm/domain/entity/response/home/ResponseMySeatRecord.kt
  domain/src/main/java/com/dpm/domain/entity/response/home/ResponseScrap.kt
  presentation/src/main/java/com/dpm/presentation/global/GlobalVariable.kt
  presentation/src/main/java/com/dpm/presentation/home/viewmodel/HomeGuiViewModel.kt
  presentation/src/main/java/com/dpm/presentation/scrap/ScrapActivity.kt
  presentation/src/main/java/com/dpm/presentation/scrap/adapter/ScrapDetailAdapter.kt
  presentation/src/main/java/com/dpm/presentation/scrap/adapter/ScrapRecordAdapter.kt
  presentation/src/main/java/com/dpm/presentation/scrap/viewmodel/ScrapViewModel.kt
  presentation/src/main/java/com/dpm/presentation/seatrecord/SeatDetailRecordFragment.kt
  presentation/src/main/java/com/dpm/presentation/seatrecord/SeatRecordActivity.kt
  presentation/src/main/java/com/dpm/presentation/viewfinder/viewmodel/StadiumDetailViewModel.kt
  presentation/src/main/res/drawable/rect_gray200_stroke_999.xml
  presentation/src/main/res/layout/activity_home.xml
  presentation/src/main/res/layout/activity_profile_edit.xml
  presentation/src/main/res/layout/activity_scrap.xml
  presentation/src/main/res/layout/activity_seat_record.xml
  presentation/src/main/res/layout/item_recent_month.xml
  presentation/src/main/res/layout/item_recent_record.xml
  presentation/src/main/res/layout/item_scrap_filter.xml
  presentation/src/main/res/layout/item_scrap_record.xml
  presentation/src/main/res/layout/item_seat_review_detail.xml
  presentation/src/main/res/values/strings.xml
Labels: 🐞Fix, 💪개발자_노균욱

#165 [FIX] 사용하지 않는 리소스 파일 삭제
  presentation/src/main/res/drawable/circle_0c0c0c_fill.xml
  presentation/src/main/res/drawable/circle_gray400_fill.xml
  presentation/src/main/res/drawable/circle_t_black02_fill.xml
  presentation/src/main/res/drawable/circlr_gray900_fill.xml
  presentation/src/main/res/drawable/ic_back.xml
  presentation/src/main/res/drawable/ic_check.xml
  presentation/src/main/res/drawable/ic_check_image.xml
  presentation/src/main/res/drawable/ic_close.xml
  presentation/src/main/res/drawable/ic_delete.xml
  presentation/src/main/res/drawable/ic_delete_image.xml
  presentation/src/main/res/drawable/ic_down.xml
  presentation/src/main/res/drawable/ic_edit.xml
  presentation/src/main/res/drawable/ic_folder_blue.xml
  presentation/src/main/res/drawable/ic_highlight_off.png
  presentation/src/main/res/drawable/ic_highlight_on.png
  presentation/src/main/res/drawable/ic_image_error.png
  presentation/src/main/res/drawable/ic_pencil.xml
  presentation/src/main/res/drawable/ic_register_sight.png
  presentation/src/main/res/drawable/ic_reload.xml
  presentation/src/main/res/drawable/ic_review_done.xml
  presentation/src/main/res/drawable/ic_sight_seeing.png
  presentation/src/main/res/drawable/ic_signup_complete.png
  presentation/src/main/res/drawable/ic_signup_complete_main.png
  presentation/src/main/res/drawable/ic_solid.xml
  presentation/src/main/res/drawable/ic_splash_big_logo.png
  presentation/src/main/res/drawable/ic_uncheck_image.xml
  presentation/src/main/res/drawable/ic_upload_seat_view_image.xml
  presentation/src/main/res/drawable/ic_upload_sight_button.xml
  presentation/src/main/res/drawable/indicator_un.xml
  presentation/src/main/res/drawable/rect_action01_fill_2.xml
  presentation/src/main/res/drawable/rect_action02_fill_6.xml
  presentation/src/main/res/drawable/rect_action03_fill_16.xml
  presentation/src/main/res/drawable/rect_gray100_fill_24.xml
  presentation/src/main/res/drawable/rect_gray100_fill_gray800_line_8.xml
  presentation/src/main/res/drawable/rect_gray100_line_6.xml
  presentation/src/main/res/drawable/rect_gray200_fill_16.xml
  presentation/src/main/res/drawable/rect_gray50_fill_30.xml
  presentation/src/main/res/drawable/rect_gray50_fill_4.xml
  presentation/src/main/res/drawable/rect_gray50_fill_warning01red_line_12.xml
  presentation/src/main/res/drawable/rect_gray900_fill_6.xml
  presentation/src/main/res/drawable/rect_gray900_fill_8.xml
  presentation/src/main/res/drawable/rect_kakao_login_40.xml
  presentation/src/main/res/drawable/rect_no_bottomright16.xml
  presentation/src/main/res/drawable/rect_no_left16.xml
  presentation/src/main/res/drawable/rect_no_right16.xml
  presentation/src/main/res/drawable/rect_no_topright16.xml
  presentation/src/main/res/drawable/rect_transparentblack01_fill_36.xml
  presentation/src/main/res/drawable/rect_warning01red_line_6.xml
  presentation/src/main/res/drawable/rect_white_fill_gray900_part_10.xml
  presentation/src/main/res/drawable/rect_white_fill_grayy100_line_6.xml
  presentation/src/main/res/drawable/sel_home_text_complete.xml
  presentation/src/main/res/drawable/sel_review_method_button.xml
  presentation/src/main/res/layout/item_home_no_record.xml
  presentation/src/main/res/layout/item_record_profile.xml
Labels: 🐞Fix, 🦖개발자_조관희

#166 Fix/#160 home qa v2
  buildSrc/build/kotlin/compileKotlin/cacheable/last-build.bin
  buildSrc/build/kotlin/compileKotlin/local-state/build-history.bin
  buildSrc/build/libs/buildSrc.jar
  domain/src/main/java/com/dpm/domain/entity/response/home/ResponseMySeatRecord.kt
  domain/src/main/java/com/dpm/domain/entity/response/home/ResponseScrap.kt
  presentation/src/main/java/com/dpm/presentation/home/HomeActivity.kt
  presentation/src/main/java/com/dpm/presentation/scrap/ScrapActivity.kt
  presentation/src/main/java/com/dpm/presentation/scrap/ScrapDetailPictureFragment.kt
  presentation/src/main/java/com/dpm/presentation/scrap/adapter/ScrapDetailAdapter.kt
  presentation/src/main/java/com/dpm/presentation/scrap/adapter/ScrapFilterAdapter.kt
  presentation/src/main/java/com/dpm/presentation/scrap/adapter/ScrapRecordAdapter.kt
  presentation/src/main/java/com/dpm/presentation/scrap/viewmodel/ScrapViewModel.kt
  presentation/src/main/java/com/dpm/presentation/seatrecord/SeatRecordActivity.kt
  presentation/src/main/java/com/dpm/presentation/seatrecord/adapter/MonthRecordAdapter.kt
  presentation/src/main/java/com/dpm/presentation/seatrecord/adapter/RecentRecordAdapter.kt
  presentation/src/main/res/drawable/rect_gray800_fill_60.xml
  presentation/src/main/res/drawable/rect_white_fill_gray200_stroke_999.xml
  presentation/src/main/res/layout/activity_scrap.xml
  presentation/src/main/res/layout/fragment_scrap_detail_picture.xml
  presentation/src/main/res/layout/item_scrap_detail.xml
  presentation/src/main/res/layout/item_scrap_filter.xml
Labels: 🐞Fix, 💪개발자_노균욱

#167 [FEAT] 시야 등록 2차 MVP 2차 QA
  buildSrc/build/kotlin/compileKotlin/cacheable/last-build.bin
  buildSrc/build/kotlin/compileKotlin/local-state/build-history.bin
  buildSrc/build/libs/buildSrc.jar
  core/designsystem/src/main/java/com/dpm/designsystem/SpotSnackBar.kt
  data/src/main/java/com/dpm/data/model/response/seatreview/ResponseSeatReviewDto.kt
  presentation/src/main/java/com/dpm/presentation/home/HomeActivity.kt
  presentation/src/main/java/com/dpm/presentation/home/viewmodel/HomeGuiViewModel.kt
  presentation/src/main/java/com/dpm/presentation/scrap/ScrapDetailPictureFragment.kt
  presentation/src/main/java/com/dpm/presentation/seatreview/ReviewActivity.kt
  presentation/src/main/java/com/dpm/presentation/seatreview/SelectViewImageActivity.kt
  presentation/src/main/java/com/dpm/presentation/seatreview/dialog/main/ReviewMySeatDialog.kt
  presentation/src/main/java/com/dpm/presentation/seatreview/dialog/main/SelectSeatDialog.kt
  presentation/src/main/java/com/dpm/presentation/seatreview/dialog/main/UnSavedDataDialog.kt
  presentation/src/main/java/com/dpm/presentation/seatreview/dialog/view/SeatShareDialog.kt
  presentation/src/main/java/com/dpm/presentation/seatreview/dialog/view/ViewUploadDialog.kt
  presentation/src/main/java/com/dpm/presentation/seatreview/sample/DialogStateManager.kt
  presentation/src/main/java/com/dpm/presentation/seatreview/sample/LevelUpManager.kt
  presentation/src/main/java/com/dpm/presentation/seatreview/viewmodel/ReviewViewModel.kt
  presentation/src/main/java/com/dpm/presentation/viewfinder/StadiumDetailActivity.kt
  presentation/src/main/res/layout/fragment_select_seat_bottom_sheet.xml
  presentation/src/main/res/layout/fragment_unsaved_data_dialog.xml
  presentation/src/main/res/raw/check.json
Labels: 🐞Fix, 🦔개발자_박민주

#171 [FIX] 시야 등록 좌석 에러 처리 보완
  buildSrc/build/kotlin/compileKotlin/cacheable/last-build.bin
  buildSrc/build/kotlin/compileKotlin/local-state/build-history.bin
  buildSrc/build/libs/buildSrc.jar
  presentation/src/main/java/com/dpm/presentation/seatreview/dialog/main/SelectSeatDialog.kt
  presentation/src/main/res/layout/fragment_select_review_type_dialog.xml
Labels: 🐞Fix, 🦔개발자_박민주

#172 [FIX] 스크랩 버그 수정
  buildSrc/build/kotlin/compileKotlin/cacheable/last-build.bin
  buildSrc/build/kotlin/compileKotlin/local-state/build-history.bin
  buildSrc/build/libs/buildSrc.jar
  presentation/src/main/java/com/dpm/presentation/scrap/ScrapDetailPictureFragment.kt
  presentation/src/main/java/com/dpm/presentation/scrap/viewmodel/ScrapViewModel.kt
  presentation/src/main/res/layout/fragment_logout_dialog.xml
  presentation/src/main/res/layout/fragment_withdraw_dialog.xml
Labels: 🐞Fix, 💪개발자_노균욱
